[platformio]
default_envs = xiao_esp32c3

[env:xiao_esp32c3]
platform = espressif32@6.12.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library@1.12.6
build_flags =
    -Wall
    -Wextra
    -Werror=return-type
